export { default as avatar } from "./avatar.webp"
export { default as palms } from "./palms.avif"
export { default as macbook } from "./macbook.avif"
export { default as waves } from "./waves.avif"
export { default as sky } from "./sky.jpg"
export { default as robot } from "./robot.jpg"